---
- name: Minimal Development Setup
  hosts: localhost
  connection: local
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
    xdg_config_home: "{{ user_home }}/.config"
    dotfiles_dir: "{{ playbook_dir }}"
    editor: "vi"
  tasks: 
    - name: System Packages
      become: true
      apt:
        name:
          - curl
          - git
          - tar
          - gzip
          - vim
          - tmux
          - nnn
        state: present
        update_cache: yes

