###########
# Bash
###########
[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["--indent", "2"] }
auto-format = true

###########
# C/C++
###########
[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]

[language-server.clangd]
command = "clangd"
args = ["--fallback-style=none"]

###########
# CSS
###########
[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[language-server.vscode-css-language-server]
config = { css = { lint = { unknownAtRules = "ignore" } } }

##############
# Dockerfile
##############
[[language]]
name = "dockerfile"
auto-format = true
formatter = { command = "dockerfmt" }

###########
# HTML
###########
[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

###########
# JS/TS
###########
[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "npx", args = [
  "prettier",
  "--parser",
  "typescript",
  "--semi",
] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "npx", args = [
  "prettier",
  "--parser",
  "typescript",
  "--semi",
] }
auto-format = true

[language-server.vscode-eslint-language-server.config]
format = true
nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionsOnSave = { mode = "all", enable = true }
experimental = { useFlatConfig = true }
problems = { shortenToSingleLine = true }
workingDirectory = { mode = "auto" }

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]
formatter = { command = "npx", args = [
  "prettier",
  "--parser",
  "typescript",
  "--semi",
] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]
formatter = { command = "npx", args = [
  "prettier",
  "--parser",
  "typescript",
  "--semi",
] }
auto-format = true

############
# JSON
############
[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

############
# Markdown
############
[[language]]
name = "markdown"
language-servers = ["marksman"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
soft-wrap.enable = true
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

############
# NGINX
############
[[language]]
name = "nginx"
file-types = [
  { glob = "sites-available/*.conf" },
  { glob = "sites-enabled/*.conf" },
  { glob = "nginx.conf" },
  { glob = "conf.d/*.conf" },
  { glob = "*.conf.template" },
  { glob = "conf.template" },
]

############
# Python
############
[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.ruff.config.settings]
logLevel = "debug"

[language-server.ty]
command = "ty"
args = ["server"]

###########
# Rust
###########
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }

############
# TOML
############
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

############
# YAML
############
[[language]]
name = "yaml"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
