###########
# Bash
###########
[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["--indent", "2"] }
auto-format = true

###########
# C/C++
###########
[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = false
language-servers = ["clangd"]
indent = { tab-width = 4, unit = "    " }

[language-server.clangd]
command = "clangd"
args = ["--fallback-style=none"]

############
# JS/TS
###########
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
format = true
nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionsOnSave = { mode = "all" }
experimental = { useFlatConfig = true }
problems = { shortenToSingleLine = true }
workingDirectory = { mode = "auto" }

############
# Markdown
############
[[language]]
name = "markdown"
language-servers = ["marksman", "github-lsp"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
soft-wrap.enable = true
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

[language-server.github-lsp]
command = "github-lsp"

############
# Python
############
[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.ruff.config.settings]
logLevel = "debug"

############
# TOML
############
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

###########
# Vue
###########
[[language]]
name = "vue"
formatter = { command = "prettier", args = ["--parser", "vue"] }
auto-format = false
language-servers = ["typescript-language-server", "tailwindcss"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/usr/local/lib/node_modules/@vue/language-server"
languages = ["vue"]

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

############
# YAML
############
[[language]]
name = "yaml"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
