---
- name: Configure global Git user settings
  git_config:
    name: "{{ git_config_item.name }}"
    value: "{{ git_config_item.value }}"
    scope: global
  loop:
    - { name: "user.name", value: "{{ user.name }}" }
    - { name: "user.email", value: "{{ user.email }}" }
  loop_control:
    loop_var: git_config_item

- name: Configure global Git operational preferences
  git_config:
    name: "{{ git_config_item.name }}"
    value: "{{ git_config_item.value }}"
    scope: global
  loop:
    - { name: "init.defaultBranch", value: "main" }
    - { name: "core.editor", value: "hx" }
    - { name: "pull.rebase", value: "true" }
    - {
        name: "core.excludesfile",
        value: "{{ paths.xdg_config_home }}/git/ignore",
      }
  loop_control:
    loop_var: git_config_item
