---
- name: Copy NVM directory
  copy:
    src: "{{ paths.dotfiles }}/nvm/"
    dest: "{{ paths.nvm }}/"
    mode: "0755"

- name: Install NVM
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
  args:
    creates: "{{ paths.nvm }}/nvm.sh"

- name: Install Node.js via NVM
  shell: . "{{ paths.nvm }}/nvm.sh" && nvm install {{ item.config.version }}
  args:
    executable: /bin/bash
