---
- name: .NET packages
  become: true
  apt:
    name:
      - dotnet-sdk-10.0
      - dotnet-runtime-10.0
    state: present
    update_cache: true

- name: Clone marksman
  git:
    repo: https://github.com/artempyanykh/marksman.git
    dest: "{{ user_home }}/marksman"
    depth: 1
    update: false

- name: Install marksman
  shell: make install
  args:
    chdir: "{{ user_home }}/marksman"
    creates: "{{ user_home }}/.local/bin/marksman"
