---
- name: Install NVM
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
  args:
    creates: "{{ nvm_dir }}/nvm.sh"

- name: Install Node.js via NVM
  shell: . "{{ nvm_dir }}/nvm.sh" && nvm install {{ node_version }}
  args:
    executable: /bin/bash
