---
- name: Install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --no-modify-path
  args:
    creates: "{{ user_home }}/.cargo/bin/rustup"

- name: Install Cargo tools
  shell: |
    set -e
    test -x "{{ user_home }}/.cargo/bin/{{ item }}" || \
      "{{ user_home }}/.cargo/bin/cargo" install --locked {{ item }}
  loop:
    - zellij
    - git-delta
