set -g mouse on
set -s escape-time 20
set -g history-limit 10000
set -g set-clipboard on

setw -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format "#{b:pane_current_path}"

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

